framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cacheBack keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cacheBack stores to the filesystem by default.
        # The data in this cacheBack should persist between deploys.
        # Other options include:

        # Redis
        #app: cacheBack.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cacheBack.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cacheBack: null
